# Generated by Django 4.0.3 on 2022-04-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
