# Generated by Django 4.0.3 on 2022-04-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
