# Generated by Django 4.0.3 on 2022-04-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_alter_comment_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='liked',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
