# Generated by Django 4.0.3 on 2022-04-03 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_image_likes_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='likes',
        ),
    ]
