# Generated by Django 4.0.3 on 2022-04-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0008_tags_delete_profile_image_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
