# Generated by Django 4.0.3 on 2022-04-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0009_rename_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
