# Generated by Django 4.0.3 on 2022-04-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0011_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tags',
        ),
    ]
